language: node_js
node_js:
  - 'stable'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install grunt-cli -g
  
 # whitelist
branches:
  only:
    - master
cache:
  directories:
  - node_modules
