name: Build && Test

on:
  workflow_call:
    inputs:
      commit_sha:
        type: string

jobs:
  only_build:

    runs-on: ubuntu-latest

    steps:
      # Prepare environment
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      # Prepare dist folder
      - run: npm install
      - run: npm run build
      
      # Ensure tests will pass
      - run: npm run test

      # Remove files
      - run: rm -rf node_modules
      - run: rm -rf .nyc_output
      - run: rm -rf .git

      # Upload artifacts to use later
      - name: Upload page artifacts
        uses: actions/upload-artifact@master
        with:
          name: ghpage-contents
          path: .