name: Task --> Test PR

on:
  workflow_call:
    inputs:
      commit_sha:
        type: string

jobs:
  test_with_coverage:

    runs-on: ubuntu-latest
    
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      # Prepare environment
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'npm'
      
      # Prepare dist folder
      - run: npm ci
      - run: npm run setup
      
      # Ensure tests will pass
      - run: npm run lint
      - run: npm run test

      # Publish code coverage in pull request
      - name: 'Report Coverage'
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: 'all'
          threshold-icons: "{0: '🔴', 60: '🟠', 90: '🟢'}"
