name: Task --> Build Artifact

on:
  workflow_call:
    inputs:
      commit_sha:
        type: string

jobs:
  build-artifact:

    runs-on: ubuntu-latest

    steps:
      # Prepare environment
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 'latest'
          cache: 'npm'
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@main
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      
      # Ensure tests will pass
      - run: npm run lint
      - run: npm run setup
      - run: npm run test

      # Prepare dist folder
      - run: npm run build

      # Prepare gh-pages contents
      - run: mv coverage/ out/coverage/

      # Upload artifacts to use later
      - name: Upload page artifacts
        uses: actions/upload-artifact@master
        with:
          name: ghpage-contents
          path: ./out
